### ISSUE TITLE
Compound use case

### ISSUE THREAD

**Issue by tvkit** [6utt3rfly/jse-eval#49]
Given the _Assignment_ plugin, I attempted to evaluate a compound expression.  The ast was constructed but  the evaluator didn't much care for it.  I was anticipating the assigned var would be passed into the subsequent expression(s): 

```
a = 1;
b = a;
c = a + b;
```
where `c` would evaluate to `2`.

Is this something that could be supported by _jse-eval_ or via a plugin? 

Noticed the volume of work you provided here and on the related projects. 👍

**Comment by 6utt3rfly** [comment]
Thanks for reporting, @tvkit ! I'm thinking that without assignment expressions, Compound support never made much sense. Hopefully this PR + release helps?

**Comment by tvkit** [comment]
Agreed... that without assignments, the preceding expression results are nebulous. 

I tested the scenario the prompted the #49 issue. Works perfectly!
