### ISSUE TITLE
how to add custom operator with logic ?

### ISSUE THREAD

**Issue by TBSten** [6utt3rfly/jse-eval#52]
I want to add custom operator with logic .

For example ,

```ts

const expr = `` ;
cosnt ast = parse(expr) ;
evaluate(ast,{});

```

In this example, I want it to return 1024, which is 2 to the 10th power, like the "^" operator in Excel.

I tried creating an original plugin like below .

```ts

const myPlugin = {
  name:"my plugin",
  init(){
    jsep.addBinaryOp("^",10);
  }
}
jsep.plugins.register(myPlugin)

```

However, I don't know where to write the essential logic of "finding exponentiation".

Please tell me how to add a custom operator with logic

**Comment by TBSten** [comment]
Was self resolved.

I was always looking at `require("jse-eval").jsep` instead of `require("jse-eval")`.

I read the README and realized that I should use `addEvaluator`.

**Comment by 6utt3rfly** [comment]
Sorry for the confusion @TBSten , but glad you figured it out! I'll try to update the readme with some better examples for extending functionality and your use case would be a great example 🙂

**Comment by TBSten** [comment]
Thank you for your response!
