### ISSUE TITLE
Properties Missing From Prototype chain

### ISSUE THREAD

**Issue by rossmeredith** [6utt3rfly/jse-eval#71]
Hi, me again!

Thanks for sorting the last bug quickly.  I've come across another issue.  Not sure if this is a bug or I've done something wrong.  I'm leaning more towards bug.

I have this set up -

```
import jsep from 'jsep';
import jsepObject from '@jsep-plugin/object';
import jsepNew from '@jsep-plugin/new';
import {
  parse,
  evaluate as safeEval,
} from 'jse-eval';

jsep.plugins.register(jsepObject);
jsep.plugins.register(jsepNew);
```

And I'm wanting to evaluate this -

```
yup.object({
  name: yup.string().required().label('Name')
}) 
```

Where I'm passing "yup" in as context.  So

```
    import * as yup from "yup";
    const javascript = "yup.object({ name: yup.string().required().label('Name')})";
    const parsed = parse(javascript);
    const context = { yup };
    const yupObject = safeEval(parsed, context);
```

My yup object is no good.  Upon inspection in the console it turns out the reason is the whole prototype chain is missing!

This is how it should look -

![image](https://user-images.githubusercontent.com/123517239/226109552-2c36123e-f24d-47e9-b30f-5ff27f43a0f8.png)

This is how it looks with the yupObject returned from jse-eval.

![image](https://user-images.githubusercontent.com/123517239/226109599-d5e4d0c6-e8e2-4fd9-9d38-be133704b284.png)

Does this point to a flaw / bug in the evaluator or am I set up wrongly?

**Comment by 6utt3rfly** [comment]
Hi @rossmeredith ! I tried adding your sample code to a node app and then comparing direct code versus jse-eval and didn't see any difference, or any issues with trying to run `validate` on the built yup schema object. jse-eval doesn't coerce tyes and only has [a check](https://github.com/6utt3rfly/jse-eval/blob/2fd129722daed8886685d1efe2b74a5a035e3bce/index.ts#L326) to guard against accessing the prototype from the expression, but that's not going on here. Maybe you can set up a more detailed example?

**Comment by rossmeredith** [comment]
Hi

Thanks for the quick response.

Apologies, it turns out that something I thought irrelevant is the problem.  "Unflatten" from the popular library "flat" is strangely causing the problem.  An issue for them therefore.

Thanks
